# TOML rule for HH FSS replacement

[[rules]]
name = "HH FSS Replacer"
priority = 1000
replacement = { mod = "Heels Sound.esm", "formID" = 0x4527 }
short_circuit = true
evaluate = "any" # "any" or "all"
conditions = [
	{ pred = "AND", preds = [
		{ pred = "actor.isFemale" },
		{ pred = "armor.feet.hasKeyword", keyword = "ClothingHH" }
	] }
]